### ISSUE TITLE
Process crashes when constructing an action_server from a sub_node

### ISSUE THREAD

**Issue by yamokosk** [ros2/rclcpp#1798]
## Bug report

- Operating System: Ubuntu 20.04.3 LTS
- Installation type: binaries
- Version or commit hash: foxy
- DDS implementation: default
- Client library (if applicable): rclcpp

#### Steps to reproduce issue
I've attached a zip file that contains a full project to demonstrate the issue. Here's the synopsis. When I create an action server with a rclcpp::Node object that is created from `create_sub_node`, the process crashes. Comment out the `#define WORKS_FINE` to reproduce.

```cpp
#define WORKS_FINE

struct Foo
{
    using Fibonacci = action_tutorials_interfaces::action::Fibonacci;
    using GoalHandleFibonacci = rclcpp_action::ServerGoalHandle<Fibonacci>;

    Foo(rclcpp::Node::SharedPtr parent_node)
    {
#ifdef WORKS_FINE
        (void) parent_node;
        _node = rclcpp::Node::make_shared("foo");
#else
        _node = parent_node->create_sub_node("foo");
#endif
        _action_server = rclcpp_action::create_server<Fibonacci>(
            _node,
            "fibonacci",
            std::bind(&Foo::handle_goal, this, std::placeholders::_1, std::placeholders::_2),
            std::bind(&Foo::handle_cancel, this, std::placeholders::_1),
            std::bind(&Foo::handle_accepted, this, std::placeholders::_1));
    };

    rclcpp_action::GoalResponse handle_goal(const rclcpp_action::GoalUUID & uuid, std::shared_ptr<const Fibonacci::Goal> goal)
    {
        (void) uuid;
        (void) goal;
        return rclcpp_action::GoalResponse::REJECT;
    }

    rclcpp_action::CancelResponse handle_cancel(const std::shared_ptr<GoalHandleFibonacci> goal_handle)
    {
        (void) goal_handle;
        return rclcpp_action::CancelResponse::REJECT;
    }

    void handle_accepted(const std::shared_ptr<GoalHandleFibonacci> goal_handle)
    {
        (void) goal_handle;
    }

    rclcpp::Node::SharedPtr _node;
    rclcpp_action::Server<Fibonacci>::SharedPtr _action_server;
};

struct Bar
{
    Bar()
    {
        _node = rclcpp::Node::make_shared("bar");
        _foo = std::make_unique<Foo>(_node);
    };

    rclcpp::Node::SharedPtr _node;
    std::unique_ptr<Foo> _foo;
};
```

#### Expected behavior
Same behavior whether using a rclcpp::Node created from `make_shared` or `create_sub_node`.

#### Actual behavior
When constructing the action server from a node created from `make_shared`, the process runs normally.

When constructing the action server from the node created from `create_sub_node`:
```
# ros2 launch construct_action_server foobar_launch.py 
[INFO] [launch]: All log files can be found below /root/.ros/log/2021-10-11-20-27-30-521763-bbdd3c2e77a7-5122
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [foobar-1]: process started with pid [5124]
[ERROR] [foobar-1]: process has died [pid 5124, exit code -11, cmd '/root/install/construct_action_server/lib/construct_action_server/foobar --ros-args -r __ns:=/'].
```

#### Additional info
[construct_action_server.zip](https://github.com/ros2/rclcpp/files/7325291/construct_action_server.zip)

**Comment by fujitatomoya** [comment]
the reason is `node_waitables_interface` is NULL, that leads to SIGSEGV.

<details>
  <summary>Click to expand gdb stack trace</summary>
  
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/root/ros2_ws/colcon_ws/install/construct_action_server/lib/construct_action_se'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  rclcpp_action::create_server<action_tutorials_interfaces::action::Fibonacci> (node_base_interface=..., node_clock_interface=...,
    node_logging_interface=..., node_waitables_interface=..., name=..., handle_goal=..., handle_cancel=..., handle_accepted=..., options=...,
    group=...) at /root/ros2_ws/colcon_ws/install/rclcpp_action/include/rclcpp_action/create_server.hpp:109
109       node_waitables_interface->add_waitable(action_server, group);
[Current thread is 1 (Thread 0x7fbe11db5f40 (LWP 348364))]
(gdb) bt
#0  rclcpp_action::create_server<action_tutorials_interfaces::action::Fibonacci> (node_base_interface=
    std::shared_ptr<rclcpp::node_interfaces::NodeBaseInterface> (use count 7, weak count 0) = {...}, node_clock_interface=
    std::shared_ptr<rclcpp::node_interfaces::NodeClockInterface> (use count 6, weak count 0) = {...}, node_logging_interface=
    std::shared_ptr<rclcpp::node_interfaces::NodeLoggingInterface> (use count 7, weak count 0) = {...}, node_waitables_interface=
    std::shared_ptr<rclcpp::node_interfaces::NodeWaitablesInterface> (empty) = {...}, name="fibonacci", handle_goal=..., handle_cancel=...,
    handle_accepted=..., options=..., group=std::shared_ptr<rclcpp::CallbackGroup> (empty) = {...})
    at /root/ros2_ws/colcon_ws/install/rclcpp_action/include/rclcpp_action/create_server.hpp:109
#1  0x000055673bb8451b in rclcpp_action::create_server<action_tutorials_interfaces::action::Fibonacci, std::shared_ptr<rclcpp::Node> > (
    node=std::shared_ptr<rclcpp::Node> (use count 2, weak count 1) = {...}, name="fibonacci", handle_goal=..., handle_cancel=...,
    handle_accepted=..., options=..., group=std::shared_ptr<rclcpp::CallbackGroup> (empty) = {...})
    at /root/ros2_ws/colcon_ws/install/rclcpp_action/include/rclcpp_action/create_server.hpp:151
#2  0x000055673bb830d6 in Foo::Foo (this=0x55673c03fa00, parent_node=std::shared_ptr<rclcpp::Node> (use count 2, weak count 1) = {...})
    at /root/ros2_ws/colcon_ws/src/ros2/construct_action_server/src/main.cpp:22
#3  0x000055673bb84841 in std::make_unique<Foo, std::shared_ptr<rclcpp::Node>&> () at /usr/include/c++/9/bits/unique_ptr.h:857
#4  0x000055673bb8334d in Bar::Bar (this=0x7ffe6b1ebe20) at /root/ros2_ws/colcon_ws/src/ros2/construct_action_server/src/main.cpp:57
#5  0x000055673bb81c17 in main (argc=1, argv=0x7ffe6b1ec198) at /root/ros2_ws/colcon_ws/src/ros2/construct_action_server/src/main.cpp:68
(gdb) info frame
Stack level 0, frame at 0x7ffe6b1eb850:
 rip = 0x55673bb86344 in rclcpp_action::create_server<action_tutorials_interfaces::action::Fibonacci>
    (/root/ros2_ws/colcon_ws/install/rclcpp_action/include/rclcpp_action/create_server.hpp:109); saved rip = 0x55673bb8451b
 called by frame at 0x7ffe6b1eb9a0
 source language c++.
 Arglist at 0x7ffe6b1eb678, args:
    node_base_interface=std::shared_ptr<rclcpp::node_interfaces::NodeBaseInterface> (use count 7, weak count 0) = {...},
    node_clock_interface=std::shared_ptr<rclcpp::node_interfaces::NodeClockInterface> (use count 6, weak count 0) = {...},
    node_logging_interface=std::shared_ptr<rclcpp::node_interfaces::NodeLoggingInterface> (use count 7, weak count 0) = {...},
    node_waitables_interface=std::shared_ptr<rclcpp::node_interfaces::NodeWaitablesInterface> (empty) = {...}, name="fibonacci", handle_goal=...,
    handle_cancel=..., handle_accepted=..., options=..., group=std::shared_ptr<rclcpp::CallbackGroup> (empty) = {...}
 Locals at 0x7ffe6b1eb678, Previous frame's sp is 0x7ffe6b1eb850
 Saved registers:
  rbx at 0x7ffe6b1eb818, rbp at 0x7ffe6b1eb840, r12 at 0x7ffe6b1eb820, r13 at 0x7ffe6b1eb828, r14 at 0x7ffe6b1eb830, r15 at 0x7ffe6b1eb838,
  rip at 0x7ffe6b1eb848
(gdb) frame 0
#0  rclcpp_action::create_server<action_tutorials_interfaces::action::Fibonacci> (
    node_base_interface=std::shared_ptr<rclcpp::node_interfaces::NodeBaseInterface> (use count 7, weak count 0) = {...},
    node_clock_interface=std::shared_ptr<rclcpp::node_interfaces::NodeClockInterface> (use count 6, weak count 0) = {...},
    node_logging_interface=std::shared_ptr<rclcpp::node_interfaces::NodeLoggingInterface> (use count 7, weak count 0) = {...},
    node_waitables_interface=std::shared_ptr<rclcpp::node_interfaces::NodeWaitablesInterface> (empty) = {...}, name="fibonacci", handle_goal=...,
    handle_cancel=..., handle_accepted=..., options=..., group=std::shared_ptr<rclcpp::CallbackGroup> (empty) = {...})
    at /root/ros2_ws/colcon_ws/install/rclcpp_action/include/rclcpp_action/create_server.hpp:109
109       node_waitables_interface->add_waitable(action_server, group);
(gdb) print node_waitables_interface
$1 = std::shared_ptr<rclcpp::node_interfaces::NodeWaitablesInterface> (empty) = {get() = 0x0}
(gdb) whatis node_waitables_interface
type = rclcpp::node_interfaces::NodeWaitablesInterface::SharedPtr
```
</details>
