### ISSUE TITLE
Failed to send request: cannot publish data

### ISSUE THREAD

**Issue by rty813** [ros2/rclcpp#2398]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 16.04
- Installation type:
  - from source
- Version or commit hash:
  - Foxy
- DDS implementation:
  - CycloneDDS
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue
I couldn't find a consistently reproducible path. It has only occurred once so far, where an exception occurred abruptly during the program execution, leading to an unexpected termination.

#### Expected behavior
no exception

#### Actual behavior
```
Exception in thread Thread-26:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/ros/foxy/install/lib/python3.8/site-packages/rclpy/executors.py", line 290, in spin
    self.spin_once()
  File "/opt/ros/foxy/install/lib/python3.8/site-packages/rclpy/executors.py", line 770, in spin_once
    self._spin_once_impl(timeout_sec)
  File "/opt/ros/foxy/install/lib/python3.8/site-packages/rclpy/executors.py", line 767, in _spin_once_impl
    future.result()
  File "/opt/ros/foxy/install/lib/python3.8/site-packages/rclpy/task.py", line 94, in result
    raise self.exception()
  File "/opt/ros/foxy/install/lib/python3.8/site-packages/rclpy/task.py", line 239, in __call__
    self._handler.send(None)
  File "/opt/ros/foxy/install/lib/python3.8/site-packages/rclpy/executors.py", line 429, in handler
    await call_coroutine(entity, arg)
  File "/opt/ros/foxy/install/lib/python3.8/site-packages/rclpy/executors.py", line 384, in _execute_service
    srv.send_response(response, header)
  File "/opt/ros/foxy/install/lib/python3.8/site-packages/rclpy/service.py", line 74, in send_response
    _rclpy.rclpy_send_response(capsule, response, header)
_rclpy.RCLError: Failed to send request: cannot publish data, at /opt/ros/foxy/src/ros2/rmw_cyclonedds/rmw_cyclonedds_cpp/src/rmw_node.cpp:3605, at /opt/ros/foxy/src/ros2/rcl/rcl/src/rcl/service.c:356
```

**Comment by Barry-Xu-2018** [comment]
This issue should be moved to https://github.com/ros2/rclpy.   
Besides, please note that Foxy has reached its EOL (Refer to https://docs.ros.org/en/rolling/Releases.html).
